2015-01-07 07:31:06,635 views INFO : Василий Пупкин was edit
2015-01-07 07:35:25,095 base WARNING : Not Found: /assets/flash/ZeroClipboard.swf
2015-01-07 07:35:25,554 base WARNING : Not Found: /contacts/favicon.ico
2015-01-07 07:35:37,287 base ERROR : Internal Server Error: /contacts/
Traceback (most recent call last):
  File "/home/alrem/env/local/lib/python2.7/site-packages/Django-1.7.1-py2.7.egg/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alrem/env/local/lib/python2.7/site-packages/Django-1.7.1-py2.7.egg/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alrem/env/local/lib/python2.7/site-packages/Django-1.7.1-py2.7.egg/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alrem/env/local/lib/python2.7/site-packages/Django-1.7.1-py2.7.egg/django/views/generic/edit.py", line 207, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/home/alrem/env/local/lib/python2.7/site-packages/Django-1.7.1-py2.7.egg/django/views/generic/edit.py", line 173, in post
    return self.form_valid(form)
  File "/home/alrem/Dropbox/pybursa/contacts/views.py", line 28, in form_valid
    [obj.recipient.email], fail_silently=False)
  File "/home/alrem/env/local/lib/python2.7/site-packages/Django-1.7.1-py2.7.egg/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/home/alrem/env/local/lib/python2.7/site-packages/Django-1.7.1-py2.7.egg/django/core/mail/message.py", line 286, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/alrem/env/local/lib/python2.7/site-packages/Django-1.7.1-py2.7.egg/django/core/mail/backends/smtp.py", line 92, in send_messages
    new_conn_created = self.open()
  File "/home/alrem/env/local/lib/python2.7/site-packages/Django-1.7.1-py2.7.egg/django/core/mail/backends/smtp.py", line 50, in open
    self.connection = connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python2.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 311, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 286, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
2015-01-07 07:36:18,875 base WARNING : Not Found: /assets/flash/ZeroClipboard.swf
2015-01-07 07:36:22,101 base WARNING : Not Found: /assets/flash/ZeroClipboard.swf
2015-01-07 07:38:11,518 views INFO : Message was send.
2015-01-07 07:42:26,517 views INFO : Coach update
2015-01-07 07:42:49,191 views INFO : Coach update
2015-01-07 07:44:43,421 views INFO : Coach ИванИванов update
2015-01-07 07:49:08,847 views INFO : CourseRuBursa was update
2015-01-07 07:50:06,561 views INFO : Create new course TestCourse фу
